### ISSUE TITLE
infer.js - Cannot call method 'propagate' of undefined

### ISSUE THREAD

**Issue by mheider** [marijnh/tern#476]
Tern crashes with this error:

```
Listening on port 49689

/usr/local/lib/node_modules/tern/lib/infer.js:905
      if (out) r.propagate(out);
                 ^
TypeError: Cannot call method 'propagate' of undefined
    at Object.Literal (/usr/local/lib/node_modules/tern/lib/infer.js:905:18)
    at infer (/usr/local/lib/node_modules/tern/lib/infer.js:1094:39)
    at inferExprVisitor.BinaryExpression (/usr/local/lib/node_modules/tern/lib/infer.js:978:9)
    at Object.BinaryExpression (/usr/local/lib/node_modules/tern/lib/infer.js:904:15)
    at infer (/usr/local/lib/node_modules/tern/lib/infer.js:1094:39)
    at Object.walk.make.Expression (/usr/local/lib/node_modules/tern/lib/infer.js:1099:7)
    at c (/usr/local/lib/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.base.ExpressionStatement (/usr/local/lib/node_modules/tern/node_modules/acorn/util/walk.js:176:5)
    at c (/usr/local/lib/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.skipThrough [as Statement] (/usr/local/lib/node_modules/tern/node_modules/acorn/util/walk.js:163:39)
```

**Comment by mheider** [comment]
That's a bit complicated. Yesterday it worked fine, today I tried working again, then this crash happened.

I am writing a plugin for [etherpad-lite](https://github.com/ether/etherpad-lite), the code that triggers this is [here](https://github.com/LSMMT/MDWE2014-MD-Etherpad/blob/master/src/static/js/hooks.js). It's not important what I type, as soon one character has been typed, tern crashes. 

Hope that helps.

**Comment by marijnh** [comment]
Pasting that code into the online demo doesn't trigger the problem. If you can reliably reproduce it, maybe add `console.log(JSON.stringify(node))` to the top of `literalType` at line 891 in `lib/infer.js`, and give me the output -- your stack trace suggests that's where the problem originates, and it does look like it could return undefined when given strange input.

**Comment by mheider** [comment]
Sorry this took so long. I have a update on this error:
```
Request: {
  "files": [
    {
      "type": "full",
      "text": "var express = require('express');\nvar path = require('path');\nvar favicon = require('serve-favicon');\nvar logger = require('morgan');\nvar cookieParser = require('cookie-parser');\nvar bodyParser = require('body-parser');\n\nvar routes = require('./routes/index');\nvar users = require('./routes/users');\n\nvar app = express();\nap\n\n// view engine setup\napp.set('views', path.join(__dirname, 'views'));\napp.set('view engine', 'jade');\n\n// uncomment after placing your favicon in /public\n//app.use(favicon(__dirname + '/public/favicon.ico'));\napp.use(logger('dev'));\napp.use(bodyParser.json());\napp.use(bodyParser.urlencoded({ extended: false }));\napp.use(cookieParser());\napp.use(express.static(path.join(__dirname, 'public')));\n\napp.use('/', routes);\napp.use('/users', users);\n\n// catch 404 and forward to error handler\napp.use(function(req, res, next) {\n    var err = new Error('Not Found');\n    rr.status = 404;\n    next(err);\n});\n\n// error handlers\n\n// development error handler\n// will print stacktrace\nif (app.get('env') === 'development') {\n    app.use(function(err, req, res, next) {\n        res.status(err.status || 500);\n        res.render('error', {\n            message: err.message,\n            error: err\n        });\n    });\n}\n\n// production error handler\n// no stacktraces leaked to user\napp.use(function(err, req, res, next) {\n    res.status(err.status || 500);\n    res.render('error', {\n        message: err.message,\n        error: {}\n    });\n});\n\n\nmodule.exports = app;\n",
      "name": "app.js"
    }
  ],
  "query": {
    "end": 324,
    "file": "app.js",
    "type": "completions",
    "includeKeywords": true,
    "depths": true,
    "types": true,
    "docs": true
  }
}

/usr/local/lib/node_modules/tern/lib/infer.js:891
    console.log(JSON.stringify(node))
                               ^
Referenceerror: node is not defined
    at literalType (/usr/local/lib/node_modules/tern/lib/infer.js:891:32)
```

**Comment by mheider** [comment]
Well reinstalling tern seems to fix the problem...

**Comment by marijnh** [comment]
I guess it has been fixed in the meantime then. Closing.
