### ISSUE TITLE
Position is out of the file.

### ISSUE THREAD

**Issue by madhavan020985** [marijnh/tern#480]
i have my tern server running on port x. Tern server loads my server.js file eagerly configured in config.loadEagerly. Ast tree on initial loading looks like,
````javascript
{ name: '/home/sk/server.js',
    parent: undefined,
    lineOffsets: null,
    ast: 
     { type: 'Program',
       start: 0,
       end: 2131,
       sourceFile: [Object],
       body: [Object] },
    text: 'var express    ... (length: 2131)',
    scope: null }
````
Then i bring up my emacs (.tern-port is configured to use running tern server), open server.js file, goto-char 689, and do Alt + . (find-definition). Now, tern regenerates the ast tree for server.js but this time, the file length becomes zero and the tree looks like,
````javascript
 { type: 'Program',
<   start: 0,
<   end: 0,
<   sourceFile: 
<    { name: 'server.js',
<      parent: null,
<      lineOffsets: null,
<      ast: [Circular],
<      text: '',
<      scope: null },
<   body: [] }
````
i can see the file has content but it throws out error as,
````javascript
TernError: Position 689 is outside of file.
<     at ternError (/home/sk/src/tern/lib/tern.js:392:15)
<     at exports.resolvePos (/home/sk/src/tern/lib/tern.js:566:8)
<     at exports.findQueryExpr (/home/sk/src/tern/lib/tern.js:777:71)
<     at Object.findDef [as run] (/home/sk/src/tern/lib/tern.js:915:16)
<     at run (/home/sk/src/tern/lib/tern.js:235:30)
<     at Object.exports.withContext (/home/sk/src/tern/lib/infer.js:658:18)
<     at infer.withContext.file.scope (/home/sk/src/tern/lib/tern.js:245:13)
<     at analyzeAll (/home/sk/src/tern/lib/tern.js:364:15)
<     at Object.done (/home/sk/src/tern/lib/tern.js:321:7)
<     at Object.signal (/home/sk/src/tern/lib/signal.js:20:60)
< Response: 400 TernError: Position 689 is outside of file.
````

**Comment by marijnh** [comment]
The `dir` parameter passed to `startServer` in `bin/tern` is the project dir, not Tern's own directory. I can't reproduce this problem, and I don't really see how it could happen, unless Tern is started from its own directory (it uses the current directory it is started from to find a project dir).
