### ISSUE TITLE
requirejs plugin: using require('module') causes ENOENT, "module.js"

### ISSUE THREAD

**Issue by Walexander** [marijnh/tern#487]
When including the `module` special dependency, the requirejs plugin attempts to load the file "module.js" instead of using the require.js module interface.
```javascript
define(function(require){
     return { module_id: require('module').id }
})
```
> condense a_module.js
> 
> fs.js:439
>  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                 ^
>Error: ENOENT, no such file or directory '...../module.js'
>    at Object.fs.openSync (fs.js:439:18)
>    at Object.fs.readFileSync (fs.js:290:15)
>    at Object.tern.Server.getFile (/usr/local/lib/node_modules/tern/bin/condense:73:39)
>    at ensureFile (/usr/local/lib/node_modules/tern/lib/tern.js:263:36)
    at Object.signal.mixin.addFile (/usr/local/lib/node_modules/tern/lib/tern.js:118:7)
>    at getInterface (/usr/local/lib/node_modules/tern/plugin/requirejs.js:92:19)
>    at data.require.computeRet (/usr/local/lib/node_modules/tern/plugin/requirejs.js:48:18)
>    at Object.exports.IsCallee.constraint.addType (/usr/local/lib/node_modules/tern/lib/infer.js:285:9)
>    at withWorklist (/usr/local/lib/node_modules/tern/lib/infer.js:698:21)
>    at Object.extend.propagate (/usr/local/lib/node_modules/tern/lib/infer.js:88:25)

Listing `module` in the array of dependencies does work correctly.

**Comment by marijnh** [comment]
Are you using the current code from git? Support for `module` was recently added.
