### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by despairblue** [marijnh/tern#510]
Though this happens with the tststs/atom-ternjs package in atom, I think it's a tern issue. This happen if inside a generator function.

```
atom-ternjs
TypeError: Cannot read property 'type' of undefined
 at Object.exports.typeFromContext (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1544:50)
 at Object.findCompletions [as run] (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:671:23)
 at run (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:212:30)
 at Object.exports.withContext (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:732:18)
 at /home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:219:13
 at analyzeAll (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:333:15)
 at doRequest (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:203:5)
 at Object.signal.mixin.request (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:143:7)
 at respond (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/bin/tern:217:10)
 at IncomingMessage. (/home/despairblue/.atom/packages/atom-ternjs/node_modules/tern/bin/tern:183:32)
```

**Comment by marijnh** [comment]
Can you give me enough context (file worked on, position where you complete) to reproduce this? As it is, I can't find a way in which this could happen (`findCompletions` always passes an `ObjectExpression` to `typeFromContext`, which, in our AST format, always has a parent, so `parentNode` returning undefined is strange.

**Comment by despairblue** [comment]
```javascript
function * test () {
  |
}
```

The `|` indicates the cursor position.

**Comment by marijnh** [comment]
Tern was producing a bogus parse tree in this case. Attached patch should fix it. There'll probably be a new Tern release in a few days.

**Comment by despairblue** [comment]
:clap: thx :smiley:
