### ISSUE TITLE
"TypeError: Cannot read property '!requirejs' of undefined" when using requirejs plugin

### ISSUE THREAD

**Issue by x-ji** [marijnh/tern#527]
I'm starting to use tern in Emacs. However, once I added "requirejs" to the "plugins" part of my .tern-project file, I get the following error whenever Emacs tries to communicate with tern:

```
Request failed: Could not start Tern server

/usr/local/lib/node_modules/tern/plugin/requirejs.js:219
    var cx = infer.cx(), interfaces = cx.definitions[data["!name"]]["!requirej
                                                                   ^
TypeError: Cannot read property '!requirejs' of undefined
    at Array.postLoadDef [as 0] (/usr/local/lib/node_modules/tern/plugin/requirejs.js:219:68)
    at runPasses (/usr/local/lib/node_modules/tern/lib/def.js:424:60)
    at doLoadEnvironment (/usr/local/lib/node_modules/tern/lib/def.js:451:5)
    at Object.exports.load (/usr/local/lib/node_modules/tern/lib/def.js:461:7)
    at /usr/local/lib/node_modules/tern/lib/infer.js:722:13
    at Object.exports.withContext (/usr/local/lib/node_modules/tern/lib/infer.js:732:18)
    at new exports.Context (/usr/local/lib/node_modules/tern/lib/infer.js:706:13)
    at Object.signal.mixin.reset (/usr/local/lib/node_modules/tern/lib/tern.js:129:17)
    at Object.exports.Server (/usr/local/lib/node_modules/tern/lib/tern.js:111:10)
    at startServer (/usr/local/lib/node_modules/tern/bin/tern:137:16)
```

Not sure what's happening here.

The following is my .tern-project file:
"titanium" is a customized file under project root.

```json
{
  "libs": [
    "titanium",
    "underscore",
    "ecma5",
    "jquery"
  ],
    "plugins": {
        "requirejs": {
            "baseURL": "./Resources",
            "paths": {}
        }
    }
}
```

**Comment by angelozerr** [comment]
It seems that you wish to use titanium https://github.com/x-cray/titanium-ternjs/blob/master/generate.py and the script seems not to generate !name.

Try to remove titanium in your libs defintion of your tern-project.

**Comment by x-ji** [comment]
Interesting. Actually, if I remove "requirejs" from "plugins", then Tern runs successfully, also providing auto-completion for all things under `Titanium` namespace. However, if I remove "titanium" from "libs", Tern also could be started succesfully...

If I have to choose one of them then I'd stick with "titanium" which provides auto-completion. But why would they conflict though.

**Comment by marijnh** [comment]
The bug is in the titanium defs though. You can just fix the titanium json file to include a `"!name": "titanium"` property (in the top-level object) and preferably submit a bug report to wherever it came from to make it spit out a valid json def file.

**Comment by x-ji** [comment]
I see. That fixed bug. Thank you.
