### ISSUE TITLE
TypeError: Cannot read property 'reuseInstances' of undefined

### ISSUE THREAD

**Issue by gfwilliams** [marijnh/tern#531]
Hi,

I just updated to the latest acorn and tern from NPM, and I now get the following error

```
/usr/lib/node_modules/tern/lib/infer.js:388
      if (cx.parent && !cx.parent.options.reuseInstances) this.noReuse = true;
                                         ^
TypeError: Cannot read property 'reuseInstances' of undefined
    at Object.exports.IsCtor.constraint.addType (/usr/lib/node_modules/tern/lib/infer.js:388:42)
    at withWorklist (/usr/lib/node_modules/tern/lib/infer.js:772:21)
    at Object.extend.propagate (/usr/lib/node_modules/tern/lib/infer.js:90:25)
    at inferExprVisitor.NewExpression (/usr/lib/node_modules/tern/lib/infer.js:1126:14)
    at Object.NewExpression (/usr/lib/node_modules/tern/lib/infer.js:990:7)
    at infer (/usr/lib/node_modules/tern/lib/infer.js:1176:39)
    at Object.walk.make.VariableDeclaration (/usr/lib/node_modules/tern/lib/infer.js:1196:11)
    at c (/usr/lib/node_modules/acorn/dist/walk.js:82:35)
    at Object.skipThrough [as Statement] (/usr/lib/node_modules/acorn/dist/walk.js:180:3)
    at c (/usr/lib/node_modules/acorn/dist/walk.js:82:35)
```

It would appear to be triggered by the following code:

```
var infer = require("tern/lib/infer");

var defs = [{
  "OneWire": {
    "!type": "fn(pin: +Pin) -> ?",
    "!doc": "Create a software OneWire implementation on the given pin",
    "!url": "http://www.espruino.com/Reference#l_OneWire_OneWire"
  }
}];
var fileContents = 'var ow = new OneWire(A1);\n'+
'var sensor = require("DS18B20").connect(ow);\n'+
'setInterval(function() {\n'+
'  console.log(sensor.getTemp());\n'+
'}, 1000);';

var cx = new infer.Context(defs, this);
infer.withContext(cx, function() {
    var ast = infer.parse(fileContents);
    infer.analyze(ast, "myID");
});
```

I've stripped this back a bit, but running it triggers the problem. Removing `defs` makes it work.

This *used to work* before I updated tern/acorn - any ideas what I'm doing wrong? Has the format of  'defs' changed?

thanks!

**Comment by marijnh** [comment]
Why are you passing the global scope object as `parent` argument to `new infer.Context`? That should either be null or a `tern.Server` instance. Remove that argument, and you should get better results.

**Comment by gfwilliams** [comment]
Thanks, it's fine now.

Sorry for wasting your time. I'm not sure how that got there - I guess I probably copied it out of the server code (or similar) and missed the `this`.
