### ISSUE TITLE
Error with ES6 (not sure) "const"

### ISSUE THREAD

**Issue by sigxcpu76** [marijnh/tern#651]
Source code:

```
use 'strict';
const E
```

When "E" is pressed:

```
Cannot read property 'type' of null at Array.isImport (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/plugin/commonjs.js:57:13)
        at Object.signal.mixin.findIn (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/plugin/modules.js:73:28)
        at Object.signal.mixin.isImport (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/plugin/modules.js:79:44)
        at Object.findCompletions (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/plugin/modules.js:261:18)
        at Object.signalReturnFirst (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/signal.js:34:27)
        at Object.findCompletions [as run] (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:668:26)
        at run (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:254:30)
        at Object.exports.withContext (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:862:18)
        at /Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:262:13 at analyzeAll (/Users/sigxcpu/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:376:15)
```

**Comment by sigxcpu76** [comment]
Same with ```let``` and ```var``` so it is not ES6 specific.

**Comment by marijnh** [comment]
Oh, that was a pretty big bug. Attached patch fixes it.
